# ADC Channel A
set_property PACKAGE_PIN W7 [get_ports ADCA_2LANES]
set_property PACKAGE_PIN V7 [get_ports ADCA_TESTPAT]
set_property PACKAGE_PIN AB7 [get_ports ADCA_PD_N]
set_property IOSTANDARD LVCMOS25 [get_ports ADCA_2LANES]
set_property IOSTANDARD LVCMOS25 [get_ports ADCA_TESTPAT]
set_property IOSTANDARD LVCMOS25 [get_ports ADCA_PD_N]

set_property PACKAGE_PIN R1 [get_ports {ADCA_CNV_P[0]}]
set_property PACKAGE_PIN P1 [get_ports {ADCA_CNV_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCA_CNV_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCA_CNV_P[0]}]
set_property DIFF_TERM TRUE [get_ports {ADCA_CNV_N[0]}]
set_property DIFF_TERM TRUE [get_ports {ADCA_CNV_P[0]}]

set_property PACKAGE_PIN R3 [get_ports {ADC_CLKA_P[0]}]
set_property PACKAGE_PIN R2 [get_ports {ADC_CLKA_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLKA_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLKA_P[0]}]
set_property DIFF_TERM TRUE [get_ports {ADC_CLKA_N[0]}]
set_property DIFF_TERM TRUE [get_ports {ADC_CLKA_P[0]}]

set_property PACKAGE_PIN U2 [get_ports {ADCA_DATA_P[0]}]
set_property PACKAGE_PIN V2 [get_ports {ADCA_DATA_N[0]}]
set_property PACKAGE_PIN W1 [get_ports {ADCA_DATA_P[1]}]
set_property PACKAGE_PIN Y1 [get_ports {ADCA_DATA_N[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCA_DATA_P[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCA_DATA_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCA_DATA_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCA_DATA_N[1]}]
set_property DIFF_TERM TRUE [get_ports {ADCA_DATA_P[0]}]
set_property DIFF_TERM TRUE [get_ports {ADCA_DATA_N[0]}]
set_property DIFF_TERM TRUE [get_ports {ADCA_DATA_P[1]}]
set_property DIFF_TERM TRUE [get_ports {ADCA_DATA_N[1]}]

# ADC Channel B
set_property PACKAGE_PIN E3 [get_ports {ADCB_2LANES[0]}]
set_property PACKAGE_PIN F3 [get_ports {ADCB_TESTPAT[0]}]
set_property PACKAGE_PIN J5 [get_ports {ADCB_PD_N[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADCB_2LANES[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADCB_TESTPAT[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {ADCB_PD_N[0]}]

set_property PACKAGE_PIN C2 [get_ports {ADCB_CNV_P[0]}]
set_property PACKAGE_PIN B2 [get_ports {ADCB_CNV_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCB_CNV_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCB_CNV_P[0]}]
set_property DIFF_TERM TRUE [get_ports {ADCB_CNV_N[0]}]
set_property DIFF_TERM TRUE [get_ports {ADCB_CNV_P[0]}]

set_property PACKAGE_PIN B1 [get_ports {ADC_CLKB_P[0]}]
set_property PACKAGE_PIN A1 [get_ports {ADC_CLKB_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLKB_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLKB_P[0]}]
set_property DIFF_TERM TRUE [get_ports {ADC_CLKB_N[0]}]
set_property DIFF_TERM TRUE [get_ports {ADC_CLKB_P[0]}]

set_property PACKAGE_PIN E1 [get_ports {ADCB_DATA_P[0]}]
set_property PACKAGE_PIN D1 [get_ports {ADCB_DATA_N[0]}]
set_property PACKAGE_PIN H4 [get_ports {ADCB_DATA_P[1]}]
set_property PACKAGE_PIN G4 [get_ports {ADCB_DATA_N[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCB_DATA_P[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCB_DATA_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCB_DATA_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCB_DATA_N[1]}]
set_property DIFF_TERM TRUE [get_ports {ADCB_DATA_P[0]}]
set_property DIFF_TERM TRUE [get_ports {ADCB_DATA_N[0]}]
set_property DIFF_TERM TRUE [get_ports {ADCB_DATA_P[1]}]
set_property DIFF_TERM TRUE [get_ports {ADCB_DATA_N[1]}]

# ACD Channel C
set_property PACKAGE_PIN M3 [get_ports ADCC_2LANES]
set_property PACKAGE_PIN K6 [get_ports ADCC_TESTPAT]
set_property PACKAGE_PIN M2 [get_ports ADCC_PD_N]
set_property IOSTANDARD LVCMOS25 [get_ports ADCC_2LANES]
set_property IOSTANDARD LVCMOS25 [get_ports ADCC_TESTPAT]
set_property IOSTANDARD LVCMOS25 [get_ports ADCC_PD_N]

set_property PACKAGE_PIN G1 [get_ports {ADCC_CNV_P[0]}]
set_property PACKAGE_PIN F1 [get_ports {ADCC_CNV_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCC_CNV_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCC_CNV_P[0]}]
set_property DIFF_TERM TRUE [get_ports {ADCC_CNV_N[0]}]
set_property DIFF_TERM TRUE [get_ports {ADCC_CNV_P[0]}]

set_property PACKAGE_PIN K4 [get_ports {ADC_CLKC_P[0]}]
set_property PACKAGE_PIN J4 [get_ports {ADC_CLKC_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLKC_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLKC_P[0]}]
set_property DIFF_TERM TRUE [get_ports {ADC_CLKC_N[0]}]
set_property DIFF_TERM TRUE [get_ports {ADC_CLKC_P[0]}]

set_property PACKAGE_PIN L3 [get_ports {ADCC_DATA_P[0]}]
set_property PACKAGE_PIN K3 [get_ports {ADCC_DATA_N[0]}]
set_property PACKAGE_PIN M1 [get_ports {ADCC_DATA_P[1]}]
set_property PACKAGE_PIN L1 [get_ports {ADCC_DATA_N[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCC_DATA_P[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCC_DATA_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCC_DATA_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCC_DATA_N[1]}]
set_property DIFF_TERM TRUE [get_ports {ADCC_DATA_P[0]}]
set_property DIFF_TERM TRUE [get_ports {ADCC_DATA_N[0]}]
set_property DIFF_TERM TRUE [get_ports {ADCC_DATA_P[1]}]
set_property DIFF_TERM TRUE [get_ports {ADCC_DATA_N[1]}]

# ADC Channel D
set_property PACKAGE_PIN V5 [get_ports ADCD_2LANES]
set_property PACKAGE_PIN R6 [get_ports ADCD_TESTPAT]
set_property PACKAGE_PIN T6 [get_ports ADCD_PD_N]
set_property IOSTANDARD LVCMOS25 [get_ports ADCD_2LANES]
set_property IOSTANDARD LVCMOS25 [get_ports ADCD_TESTPAT]
set_property IOSTANDARD LVCMOS25 [get_ports ADCD_PD_N]

set_property PACKAGE_PIN W2 [get_ports {ADCD_CNV_P[0]}]
set_property PACKAGE_PIN Y2 [get_ports {ADCD_CNV_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCD_CNV_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCD_CNV_P[0]}]
set_property DIFF_TERM TRUE [get_ports {ADCD_CNV_N[0]}]
set_property DIFF_TERM TRUE [get_ports {ADCD_CNV_P[0]}]

set_property PACKAGE_PIN AA1 [get_ports {ADC_CLKD_P[0]}]
set_property PACKAGE_PIN AB1 [get_ports {ADC_CLKD_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLKD_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADC_CLKD_P[0]}]
set_property DIFF_TERM TRUE [get_ports {ADC_CLKD_N[0]}]
set_property DIFF_TERM TRUE [get_ports {ADC_CLKD_P[0]}]

set_property PACKAGE_PIN AB3 [get_ports {ADCD_DATA_P[0]}]
set_property PACKAGE_PIN AB2 [get_ports {ADCD_DATA_N[0]}]
set_property PACKAGE_PIN AA8 [get_ports {ADCD_DATA_P[1]}]
set_property PACKAGE_PIN AB8 [get_ports {ADCD_DATA_N[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCD_DATA_P[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCD_DATA_N[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCD_DATA_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {ADCD_DATA_N[1]}]
set_property DIFF_TERM TRUE [get_ports {ADCD_DATA_P[0]}]
set_property DIFF_TERM TRUE [get_ports {ADCD_DATA_N[0]}]
set_property DIFF_TERM TRUE [get_ports {ADCD_DATA_P[1]}]
set_property DIFF_TERM TRUE [get_ports {ADCD_DATA_N[1]}]

# CCD_VDRAIN

set_property PACKAGE_PIN E14 [get_ports CDD_VDRAIN_EN]
set_property PACKAGE_PIN E13 [get_ports CCD_VDRAIN_DIGPOT_SYNC_N]
#set_property PACKAGE_PIN C14 [get_ports CCD_VDRAIN_DIGPOT_RDY]
set_property PACKAGE_PIN C15 [get_ports CCD_VDRAIN_DIGPOT_SDO]
set_property IOSTANDARD LVCMOS25 [get_ports CDD_VDRAIN_EN]
set_property IOSTANDARD LVCMOS25 [get_ports CCD_VDRAIN_DIGPOT_SYNC_N]
#set_property IOSTANDARD LVCMOS25 [get_ports CCD_VDRAIN_DIGPOT_RDY]
set_property IOSTANDARD LVCMOS25 [get_ports CCD_VDRAIN_DIGPOT_SDO]

# CCD_VDD
set_property PACKAGE_PIN B15 [get_ports CCD_VDD_EN]
set_property PACKAGE_PIN D15 [get_ports CCD_VDD_DIGPOT_SYNC_N]
#set_property PACKAGE_PIN D16 [get_ports CCD_VDD_DIGPOT_RDY]
set_property PACKAGE_PIN D14 [get_ports CCD_VDD_DIGPOT_SDO]
set_property IOSTANDARD LVCMOS25 [get_ports CCD_VDD_EN]
set_property IOSTANDARD LVCMOS25 [get_ports CCD_VDD_DIGPOT_SYNC_N]
#set_property IOSTANDARD LVCMOS25 [get_ports CCD_VDD_DIGPOT_RDY]
set_property IOSTANDARD LVCMOS25 [get_ports CCD_VDD_DIGPOT_SDO]

# CCD_VR
set_property PACKAGE_PIN A16 [get_ports CCD_VR_EN]
set_property PACKAGE_PIN A15 [get_ports CCD_VR_DIGPOT_SYNC_N]
#set_property PACKAGE_PIN C13 [get_ports CCD_VR_DIGPOT_RDY]
set_property PACKAGE_PIN B13 [get_ports CCD_VR_DIGPOT_SDO]
set_property IOSTANDARD LVCMOS25 [get_ports CCD_VR_EN]
set_property IOSTANDARD LVCMOS25 [get_ports CCD_VR_DIGPOT_SYNC_N]
#set_property IOSTANDARD LVCMOS25 [get_ports CCD_VR_DIGPOT_RDY]
set_property IOSTANDARD LVCMOS25 [get_ports CCD_VR_DIGPOT_SDO]

# CCD_VSUB
set_property PACKAGE_PIN D17 [get_ports CCD_VSUB_EN]
set_property PACKAGE_PIN B18 [get_ports CCD_VSUB_DIGPOT_SYNC_N]
#set_property PACKAGE_PIN A14 [get_ports CCD_VSUB_DIGPOT_RDY]
set_property PACKAGE_PIN B17 [get_ports CCD_VSUB_DIGPOT_SDO]
set_property IOSTANDARD LVCMOS25 [get_ports CCD_VSUB_EN]
set_property IOSTANDARD LVCMOS25 [get_ports CCD_VSUB_DIGPOT_SYNC_N]
#set_property IOSTANDARD LVCMOS25 [get_ports CCD_VSUB_DIGPOT_RDY]
set_property IOSTANDARD LVCMOS25 [get_ports CCD_VSUB_DIGPOT_SDO]

# DIGPOT Shared Signals
set_property PACKAGE_PIN F13 [get_ports DIGPOT_RST_N]
set_property PACKAGE_PIN F14 [get_ports DIGPOT_DIN]
set_property PACKAGE_PIN F16 [get_ports DIGPOT_SCLK]
set_property IOSTANDARD LVCMOS25 [get_ports DIGPOT_RST_N]
set_property IOSTANDARD LVCMOS25 [get_ports DIGPOT_DIN]
set_property IOSTANDARD LVCMOS25 [get_ports DIGPOT_SCLK]

# VOLT_SW
set_property PACKAGE_PIN E18 [get_ports VOLT_SW_CLR]
set_property PACKAGE_PIN B20 [get_ports VOLT_SW_LE_N]
set_property PACKAGE_PIN A20 [get_ports VOLT_SW_CLK]
set_property PACKAGE_PIN A18 [get_ports VOLT_SW_DIN]
set_property PACKAGE_PIN A19 [get_ports VOLT_SW_DOUT]
set_property IOSTANDARD LVCMOS25 [get_ports VOLT_SW_CLR]
set_property IOSTANDARD LVCMOS25 [get_ports VOLT_SW_LE_N]
set_property IOSTANDARD LVCMOS25 [get_ports VOLT_SW_CLK]
set_property IOSTANDARD LVCMOS25 [get_ports VOLT_SW_DIN]
set_property IOSTANDARD LVCMOS25 [get_ports VOLT_SW_DOUT]

# DAC
set_property PACKAGE_PIN AA4 [get_ports DAC_LDAC_N]
set_property PACKAGE_PIN V4 [get_ports DAC_CLR_N]
set_property PACKAGE_PIN W4 [get_ports DAC_RESET_N]
set_property IOSTANDARD LVCMOS25 [get_ports DAC_LDAC_N]
set_property IOSTANDARD LVCMOS25 [get_ports DAC_CLR_N]
set_property IOSTANDARD LVCMOS25 [get_ports DAC_RESET_N]

set_property PACKAGE_PIN R4 [get_ports {DAC_SYNC_N[0]}]
set_property PACKAGE_PIN T4 [get_ports DAC_SCLK]
set_property PACKAGE_PIN T5 [get_ports DAC_SDI]
set_property PACKAGE_PIN U5 [get_ports DAC_SDO]
set_property IOSTANDARD LVCMOS25 [get_ports {DAC_SYNC_N[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports DAC_SCLK]
set_property IOSTANDARD LVCMOS25 [get_ports DAC_SDI]
set_property IOSTANDARD LVCMOS25 [get_ports DAC_SDO]

#set_property PACKAGE_PIN W6 [get_ports DAC_B\U\S\Y\]
#set_property IOSTANDARD LVCMOS25 [get_ports DAC_B\U\S\Y\]
#
# TGL_* (DAC switches)
set_property PACKAGE_PIN V13 [get_ports DAC_SW_EN]
set_property IOSTANDARD LVCMOS25 [get_ports DAC_SW_EN]

#set_property PACKAGE_PIN AA10 [get_ports TGL_SPR_CLKA]
#set_property IOSTANDARD LVCMOS25 [get_ports TGL_SPR_CLKA]

set_property PACKAGE_PIN AB16 [get_ports TGL_H1A]
set_property PACKAGE_PIN AB17 [get_ports TGL_H2A]
set_property PACKAGE_PIN AA13 [get_ports TGL_H3A]
set_property PACKAGE_PIN AA14 [get_ports TGL_SWA]
set_property PACKAGE_PIN AB11 [get_ports TGL_RGA]
set_property PACKAGE_PIN AA9 [get_ports TGL_OGA]
set_property PACKAGE_PIN Y17 [get_ports TGL_V1C]
set_property PACKAGE_PIN Y16 [get_ports TGL_V2C]
set_property PACKAGE_PIN AA16 [get_ports TGL_V3C]
set_property PACKAGE_PIN Y13 [get_ports TGL_TG]
set_property PACKAGE_PIN AB13 [get_ports TGL_H1B]
set_property PACKAGE_PIN AA15 [get_ports TGL_H2B]
set_property PACKAGE_PIN AB15 [get_ports TGL_H3B]
set_property PACKAGE_PIN W14 [get_ports TGL_SWB]
set_property PACKAGE_PIN AB12 [get_ports TGL_RGB]
set_property PACKAGE_PIN AB10 [get_ports TGL_OGB]
set_property PACKAGE_PIN Y14 [get_ports TGL_DG]
set_property IOSTANDARD LVCMOS25 [get_ports TGL_H1A]
set_property IOSTANDARD LVCMOS25 [get_ports TGL_H2A]
set_property IOSTANDARD LVCMOS25 [get_ports TGL_H3A]
set_property IOSTANDARD LVCMOS25 [get_ports TGL_SWA]
set_property IOSTANDARD LVCMOS25 [get_ports TGL_RGA]
set_property IOSTANDARD LVCMOS25 [get_ports TGL_OGA]
set_property IOSTANDARD LVCMOS25 [get_ports TGL_V1C]
set_property IOSTANDARD LVCMOS25 [get_ports TGL_V2C]
set_property IOSTANDARD LVCMOS25 [get_ports TGL_V3C]
set_property IOSTANDARD LVCMOS25 [get_ports TGL_TG]
set_property IOSTANDARD LVCMOS25 [get_ports TGL_H1B]
set_property IOSTANDARD LVCMOS25 [get_ports TGL_H2B]
set_property IOSTANDARD LVCMOS25 [get_ports TGL_H3B]
set_property IOSTANDARD LVCMOS25 [get_ports TGL_SWB]
set_property IOSTANDARD LVCMOS25 [get_ports TGL_RGB]
set_property IOSTANDARD LVCMOS25 [get_ports TGL_OGB]
set_property IOSTANDARD LVCMOS25 [get_ports TGL_DG]

# SPARE_SW
#set_property PACKAGE_PIN AA20 [get_ports SPARE_SW0]
#set_property PACKAGE_PIN AA21 [get_ports SPARE_SW1]
#set_property PACKAGE_PIN Y21 [get_ports SPARE_SW2]
#set_property PACKAGE_PIN Y22 [get_ports SPARE_SW3]
set_property PACKAGE_PIN AB21 [get_ports SPARE_SW4]
#set_property IOSTANDARD LVCMOS25 [get_ports SPARE_SW0]
#set_property IOSTANDARD LVCMOS25 [get_ports SPARE_SW1]
#set_property IOSTANDARD LVCMOS25 [get_ports SPARE_SW2]
#set_property IOSTANDARD LVCMOS25 [get_ports SPARE_SW3]
set_property IOSTANDARD LVCMOS25 [get_ports SPARE_SW4]

# LEDS
set_property PACKAGE_PIN K14 [get_ports LED0]
set_property PACKAGE_PIN K17 [get_ports LED1]
set_property PACKAGE_PIN L14 [get_ports LED2]
set_property PACKAGE_PIN L15 [get_ports LED3]
set_property PACKAGE_PIN K16 [get_ports LED4]
set_property PACKAGE_PIN M16 [get_ports LED5]
set_property IOSTANDARD LVCMOS25 [get_ports LED0]
set_property IOSTANDARD LVCMOS25 [get_ports LED1]
set_property IOSTANDARD LVCMOS25 [get_ports LED2]
set_property IOSTANDARD LVCMOS25 [get_ports LED3]
set_property IOSTANDARD LVCMOS25 [get_ports LED4]
set_property IOSTANDARD LVCMOS25 [get_ports LED5]

# ETHERNET
set_property PACKAGE_PIN W20 [get_ports ENET_GTXCLK]
set_property PACKAGE_PIN P17 [get_ports ENET_TXEN]
set_property PACKAGE_PIN P15 [get_ports ENET_TXER]
set_property IOSTANDARD LVCMOS25 [get_ports ENET_GTXCLK]
set_property IOSTANDARD LVCMOS25 [get_ports ENET_TXEN]
set_property IOSTANDARD LVCMOS25 [get_ports ENET_TXER]

set_property PACKAGE_PIN Y19 [get_ports ENET_TX0]
set_property PACKAGE_PIN AB20 [get_ports ENET_TX1]
set_property PACKAGE_PIN AA19 [get_ports ENET_TX2]
set_property PACKAGE_PIN V18 [get_ports ENET_TX3]
set_property PACKAGE_PIN V19 [get_ports ENET_TX4]
set_property PACKAGE_PIN V17 [get_ports ENET_TX5]
set_property PACKAGE_PIN W17 [get_ports ENET_TX6]
set_property PACKAGE_PIN AA18 [get_ports ENET_TX7]
set_property IOSTANDARD LVCMOS25 [get_ports ENET_TX0]
set_property IOSTANDARD LVCMOS25 [get_ports ENET_TX1]
set_property IOSTANDARD LVCMOS25 [get_ports ENET_TX2]
set_property IOSTANDARD LVCMOS25 [get_ports ENET_TX3]
set_property IOSTANDARD LVCMOS25 [get_ports ENET_TX4]
set_property IOSTANDARD LVCMOS25 [get_ports ENET_TX5]
set_property IOSTANDARD LVCMOS25 [get_ports ENET_TX6]
set_property IOSTANDARD LVCMOS25 [get_ports ENET_TX7]

set_property PACKAGE_PIN T18 [get_ports ENET_RX0]
set_property PACKAGE_PIN P14 [get_ports ENET_RX1]
set_property PACKAGE_PIN R14 [get_ports ENET_RX2]
set_property PACKAGE_PIN U18 [get_ports ENET_RX3]
set_property PACKAGE_PIN R16 [get_ports ENET_RX4]
set_property PACKAGE_PIN U17 [get_ports ENET_RX5]
set_property PACKAGE_PIN AB18 [get_ports ENET_RX6]
set_property PACKAGE_PIN N17 [get_ports ENET_RX7]
set_property IOSTANDARD LVCMOS25 [get_ports ENET_RX0]
set_property IOSTANDARD LVCMOS25 [get_ports ENET_RX1]
set_property IOSTANDARD LVCMOS25 [get_ports ENET_RX2]
set_property IOSTANDARD LVCMOS25 [get_ports ENET_RX3]
set_property IOSTANDARD LVCMOS25 [get_ports ENET_RX4]
set_property IOSTANDARD LVCMOS25 [get_ports ENET_RX5]
set_property IOSTANDARD LVCMOS25 [get_ports ENET_RX6]
set_property IOSTANDARD LVCMOS25 [get_ports ENET_RX7]

set_property PACKAGE_PIN W19 [get_ports ENET_RXCLK]
set_property PACKAGE_PIN R18 [get_ports ENET_RXDV]
#set_property PACKAGE_PIN N13 [get_ports ENET_RXER]
set_property IOSTANDARD LVCMOS25 [get_ports ENET_RXCLK]
set_property IOSTANDARD LVCMOS25 [get_ports ENET_RXDV]
#set_property IOSTANDARD LVCMOS25 [get_ports ENET_RXER]
#
# POWER SYNC
#set_property PACKAGE_PIN D20 [get_ports 1V0_SYNC]
#set_property PACKAGE_PIN C22 [get_ports 1V8_SYNC]
#set_property PACKAGE_PIN C20 [get_ports 2V5_SYNC]
#set_property PACKAGE_PIN B22 [get_ports 3V3_SYNC]
#set_property IOSTANDARD LVCMOS25 [get_ports 1V0_SYNC]
#set_property IOSTANDARD LVCMOS25 [get_ports 1V8_SYNC]
#set_property IOSTANDARD LVCMOS25 [get_ports 2V5_SYNC]
#set_property IOSTANDARD LVCMOS25 [get_ports 3V3_SYNC]
#
# TELEMETRY
set_property PACKAGE_PIN Y12 [get_ports TEL_MUXEN0]
set_property PACKAGE_PIN W11 [get_ports TEL_MUXEN1]
set_property PACKAGE_PIN W12 [get_ports TEL_MUXEN2]
set_property IOSTANDARD LVCMOS25 [get_ports TEL_MUXEN0]
set_property IOSTANDARD LVCMOS25 [get_ports TEL_MUXEN1]
set_property IOSTANDARD LVCMOS25 [get_ports TEL_MUXEN2]

set_property PACKAGE_PIN V10 [get_ports TEL_MUXA0]
set_property PACKAGE_PIN W10 [get_ports TEL_MUXA1]
set_property PACKAGE_PIN Y11 [get_ports TEL_MUXA2]
set_property IOSTANDARD LVCMOS25 [get_ports TEL_MUXA0]
set_property IOSTANDARD LVCMOS25 [get_ports TEL_MUXA1]
set_property IOSTANDARD LVCMOS25 [get_ports TEL_MUXA2]

set_property PACKAGE_PIN G2 [get_ports TEL_SCLK]
set_property PACKAGE_PIN L4 [get_ports TEL_DIN]
set_property PACKAGE_PIN Y7 [get_ports {TEL_CS_N[0]}]
set_property PACKAGE_PIN U7 [get_ports TEL_DOUT]
set_property IOSTANDARD LVCMOS25 [get_ports TEL_SCLK]
set_property IOSTANDARD LVCMOS25 [get_ports TEL_DIN]
set_property IOSTANDARD LVCMOS25 [get_ports {TEL_CS_N[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports TEL_DOUT]

# USER_CLK
#set_property PACKAGE_PIN W21 [get_ports USER_CLK_SDA]
#set_property PACKAGE_PIN T20 [get_ports USER_CLK_SCL]
#set_property IOSTANDARD LVCMOS25 [get_ports USER_CLK_SDA]
#set_property IOSTANDARD LVCMOS25 [get_ports USER_CLK_SCL]
#
# USER Clock
set_property PACKAGE_PIN Y18 [get_ports USER_CLK]
set_property IOSTANDARD LVCMOS25 [get_ports USER_CLK]
#
# USB_UART
set_property PACKAGE_PIN P19 [get_ports USB_UART_TX]
set_property PACKAGE_PIN R19 [get_ports USB_UART_RX]
#set_property PACKAGE_PIN T21 [get_ports USB_UART_RTS]
#set_property PACKAGE_PIN U21 [get_ports USB_UART_CTS]
set_property IOSTANDARD LVCMOS25 [get_ports USB_UART_TX]
set_property IOSTANDARD LVCMOS25 [get_ports USB_UART_RX]
#set_property IOSTANDARD LVCMOS25 [get_ports USB_UART_RTS]
#set_property IOSTANDARD LVCMOS25 [get_ports USB_UART_CTS]
#
# FAN Control
#set_property PACKAGE_PIN V20 [get_ports FAN_CTRL]
#set_property IOSTANDARD LVCMOS25 [get_ports FAN_CTRL]
#
# MICTOR Connector Digital Analyzer (J13)
#set_property PACKAGE_PIN G13 [get_ports ANA_CLK]
#set_property IOSTANDARD LVCMOS25 [get_ports ANA_CLK]
#
set_property PACKAGE_PIN G18 [get_ports ANA_0]
set_property PACKAGE_PIN G17 [get_ports ANA_1]
set_property PACKAGE_PIN L20 [get_ports ANA_2]
set_property PACKAGE_PIN L21 [get_ports ANA_3]
set_property PACKAGE_PIN K21 [get_ports ANA_4]
set_property PACKAGE_PIN K22 [get_ports ANA_5]
set_property PACKAGE_PIN G16 [get_ports ANA_6]
set_property PACKAGE_PIN H18 [get_ports ANA_7]
set_property PACKAGE_PIN G15 [get_ports ANA_8]
set_property PACKAGE_PIN H17 [get_ports ANA_9]
set_property PACKAGE_PIN J21 [get_ports ANA_10]
set_property PACKAGE_PIN J22 [get_ports ANA_11]
set_property PACKAGE_PIN J20 [get_ports ANA_12]
set_property PACKAGE_PIN H20 [get_ports ANA_13]
set_property PACKAGE_PIN H22 [get_ports ANA_14]
set_property PACKAGE_PIN G20 [get_ports ANA_15]
set_property PACKAGE_PIN N22 [get_ports ANA_16]
#set_property PACKAGE_PIN M21 [get_ports ANA_17]
#set_property PACKAGE_PIN M22 [get_ports ANA_18]
#set_property PACKAGE_PIN L19 [get_ports ANA_19]
#set_property PACKAGE_PIN K18 [get_ports ANA_20]
#set_property PACKAGE_PIN J14 [get_ports ANA_21]
#set_property PACKAGE_PIN J19 [get_ports ANA_22]
#set_property PACKAGE_PIN M18 [get_ports ANA_23]
#set_property PACKAGE_PIN L18 [get_ports ANA_24]
#set_property PACKAGE_PIN K19 [get_ports ANA_25]
#set_property PACKAGE_PIN H13 [get_ports ANA_26]
#set_property PACKAGE_PIN H14 [get_ports ANA_27]
#set_property PACKAGE_PIN J15 [get_ports ANA_28]
#set_property PACKAGE_PIN J16 [get_ports ANA_29]
#set_property PACKAGE_PIN H19 [get_ports ANA_30]
#set_property PACKAGE_PIN H15 [get_ports ANA_31]
set_property IOSTANDARD LVCMOS25 [get_ports ANA_0]
set_property IOSTANDARD LVCMOS25 [get_ports ANA_1]
set_property IOSTANDARD LVCMOS25 [get_ports ANA_2]
set_property IOSTANDARD LVCMOS25 [get_ports ANA_3]
set_property IOSTANDARD LVCMOS25 [get_ports ANA_4]
set_property IOSTANDARD LVCMOS25 [get_ports ANA_5]
set_property IOSTANDARD LVCMOS25 [get_ports ANA_6]
set_property IOSTANDARD LVCMOS25 [get_ports ANA_7]
set_property IOSTANDARD LVCMOS25 [get_ports ANA_8]
set_property IOSTANDARD LVCMOS25 [get_ports ANA_9]
set_property IOSTANDARD LVCMOS25 [get_ports ANA_10]
set_property IOSTANDARD LVCMOS25 [get_ports ANA_11]
set_property IOSTANDARD LVCMOS25 [get_ports ANA_12]
set_property IOSTANDARD LVCMOS25 [get_ports ANA_13]
set_property IOSTANDARD LVCMOS25 [get_ports ANA_14]
set_property IOSTANDARD LVCMOS25 [get_ports ANA_15]
set_property IOSTANDARD LVCMOS25 [get_ports ANA_16]
#set_property IOSTANDARD LVCMOS25 [get_ports ANA_17]
#set_property IOSTANDARD LVCMOS25 [get_ports ANA_18]
#set_property IOSTANDARD LVCMOS25 [get_ports ANA_19]
#set_property IOSTANDARD LVCMOS25 [get_ports ANA_20]
#set_property IOSTANDARD LVCMOS25 [get_ports ANA_21]
#set_property IOSTANDARD LVCMOS25 [get_ports ANA_22]
#set_property IOSTANDARD LVCMOS25 [get_ports ANA_23]
#set_property IOSTANDARD LVCMOS25 [get_ports ANA_24]
#set_property IOSTANDARD LVCMOS25 [get_ports ANA_25]
#set_property IOSTANDARD LVCMOS25 [get_ports ANA_26]
#set_property IOSTANDARD LVCMOS25 [get_ports ANA_27]
#set_property IOSTANDARD LVCMOS25 [get_ports ANA_28]
#set_property IOSTANDARD LVCMOS25 [get_ports ANA_29]
#set_property IOSTANDARD LVCMOS25 [get_ports ANA_30]
#set_property IOSTANDARD LVCMOS25 [get_ports ANA_31]

#set_input_delay -clock [get_clocks [get_clocks -of_objects [get_pins ublaze_subsystem_i/ad_4ch/inst/ad_controller_4ch_i/clk_wiz/inst/mmcm_adv_inst/CLKOUT0]]] 5.000 [get_ports ADC_DA_B_P]
#set_input_delay -clock [get_clocks [get_clocks -of_objects [get_pins ublaze_subsystem_i/ad_4ch/inst/ad_controller_4ch_i/clk_wiz/inst/mmcm_adv_inst/CLKOUT0]]] 1.000 [get_ports ADC_DCOB_P]

#set_property IODELAY_GROUP adc_ad [get_cells ublaze_subsystem_i/adc_a/U0/sio1_1_i/selectio_wiz_0/inst/delayctrl]
#set_property IODELAY_GROUP adc_ad [get_cells ublaze_subsystem_i/adc_a/U0/sio1_1_i/selectio_wiz_0/inst/pins[0].idelaye2_bus]
#set_property IODELAY_GROUP adc_ad [get_cells ublaze_subsystem_i/adc_a/U0/sio1_1_i/selectio_wiz_0/inst/pins[1].idelaye2_bus]

#set_property IODELAY_GROUP adc_b [get_cells ublaze_subsystem_i/adc_b/U0/sio1_1_i/selectio_wiz_0/inst/delayctrl]
#set_property IODELAY_GROUP adc_b [get_cells ublaze_subsystem_i/adc_b/U0/sio1_1_i/selectio_wiz_0/inst/pins[0].idelaye2_bus]
#set_property IODELAY_GROUP adc_b [get_cells ublaze_subsystem_i/adc_b/U0/sio1_1_i/selectio_wiz_0/inst/pins[1].idelaye2_bus]

#set_property IODELAY_GROUP adc_c [get_cells ublaze_subsystem_i/adc_c/U0/sio1_1_i/selectio_wiz_0/inst/delayctrl]
#set_property IODELAY_GROUP adc_c [get_cells ublaze_subsystem_i/adc_c/U0/sio1_1_i/selectio_wiz_0/inst/pins[0].idelaye2_bus]
#set_property IODELAY_GROUP adc_c [get_cells ublaze_subsystem_i/adc_c/U0/sio1_1_i/selectio_wiz_0/inst/pins[1].idelaye2_bus]

#set_property IODELAY_GROUP adc_ad [get_cells ublaze_subsystem_i/adc_d/U0/sio1_1_i/selectio_wiz_0/inst/delayctrl]
#set_property IODELAY_GROUP adc_ad [get_cells ublaze_subsystem_i/adc_d/U0/sio1_1_i/selectio_wiz_0/inst/pins[0].idelaye2_bus]
#set_property IODELAY_GROUP adc_ad [get_cells ublaze_subsystem_i/adc_d/U0/sio1_1_i/selectio_wiz_0/inst/pins[1].idelaye2_bus]

# Properties for Bitstream generation for external Flash usage.
set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.EXTMASTERCCLK_EN DISABLE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 40 [current_design]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
